export const paketData = [
  {
    title: "Paket Data Telkomsel 6GB",
    image: "/paket-telkomsel.png",
    price: "Rp40.000",
    category: "Paket Data",
    discount: "10%",
    className: "object-cover",
  },
  {
    title: "Paket Data XL 15GB",
    image: "/paket-xl.jpeg",
    price: "Rp80.000",
    category: "Paket Data",
    discount: "8%",
    className: "",
  },
  {
    title: "Paket Data Indosat 10GB",
    image: "/data-indosat.jpeg",
    price: "Rp75.000",
    category: "Paket Data",
    discount: "5%",
    className: "object-cover",
  },
  {
    title: "Paket Data Tri 20GB",
    image: "/paket-tri.jpeg",
    price: "Rp70.000",
    category: "Paket Data",
    discount: "12%",
    className: "object-cover",
  },
  {
    title: "Paket Data Smartfren 30GB",
    image: "/paket-smartfren.jpeg",
    price: "Rp85.000",
    category: "Paket Data",
    discount: "15%",
    className: "object-cover",
  },
];

export const pulsa = [
  {
    title: "Pulsa Telkomsel",
    image: "/pulsa-telkomsel.jpeg",
    price: "Rp25.000",
    category: "Pulsa",
    discount: "10%",
    className: "object-cover",
  },
  {
    title: "Pulsa XL",
    image: "/pulsa-xl.jpeg",
    price: "Rp50.000",
    category: "Pulsa",
    discount: "3%",
    className: "",
  },
  {
    title: "Pulsa Indosat",
    image: "/pulsa-indosat.jpeg",
    price: "Rp100.000",
    category: "Pulsa",
    discount: "5%",
    className: "",
  },
  {
    title: "Pulsa Axis",
    image: "/pulsa-axis.jpeg",
    price: "Rp20.000",
    category: "Pulsa",
    discount: "2%",
    className: "object-cover",
  },
  {
    title: "Pulsa Tri",
    image: "/paket-tri.jpeg",
    price: "Rp40.000",
    category: "Pulsa",
    discount: "3%",
    className: "object-cover",
  },
  {
    title: "Pulsa Smartfren",
    image: "/paket-smartfren.jpeg",
    price: "Rp30.000",
    category: "Pulsa",
    discount: "4%",
    className: "object-cover",
  },
];

export const voucherGame = [
  {
    title: "Mobile Legends 86 Diamonds",
    image: "/mobile-legend.jpeg",
    price: "Rp22.000",
    category: "Game",
    discount: "5%",
  },
  {
    title: "PUBG Mobile 150 UC",
    image: "/pubg.jpeg",
    price: "Rp30.000",
    category: "Game",
    discount: "3%",
  },
  {
    title: "Genshin Impact 300 Genesis",
    image: "/genshin-impact.jpeg",
    price: "Rp790.000",
    category: "Game",
    discount: "7%",
  },
  {
    title: "Valorant 1000 Points",
    image: "/valorant.jpeg",
    price: "Rp120.000",
    category: "Game",
    discount: "4%",
  },
  {
    title: "Call of Duty Mobile 400 CP",
    image: "/call-of-duty.jpeg",
    price: "Rp60.000",
    category: "Game",
    discount: "6%",
  },
  {
    title: "Apex Legends 1000 Coins",
    image: "/apex-legends.jpeg",
    price: "Rp110.000",
    category: "Game",
    discount: "5%",
  },
  {
    title: "Ragnarok M 60 Big Cat Coins",
    image: "/ragnarok-m.jpeg",
    price: "Rp18.000",
    category: "Game",
    discount: "2%",
  },
];

export const voucherDigital = [
  {
    title: "Netflix 1 Bulan",
    image: "/netflix.jpeg",
    price: "Rp159.000",
    category: "Streaming",
    discount: "10%",
  },
  {
    title: "Spotify Premium 1 Bulan",
    image: "/spotify.jpeg",
    price: "Rp54.000",
    category: "Streaming",
    discount: "5%",
  },
  {
    title: "Disney+ Hotstar 1 Bulan",
    image: "/disney-hotstar.jpeg",
    price: "Rp39.000",
    category: "Streaming",
    discount: "8%",
  },
  {
    title: "YouTube Premium 1 Bulan",
    image: "/youtube.jpeg",
    price: "Rp29.000",
    category: "Streaming",
    discount: "8%",
  },
  {
    title: "Spotify Premium 3 Bulan",
    image: "/spotify.jpeg",
    price: "Rp159.000",
    category: "Streaming",
    discount: "7%",
  },
  {
    title: "Disney+ Hotstar 3 Bulan",
    image: "/disney-hotstar.jpeg",
    price: "Rp159.000",
    category: "Streaming",
    discount: "5%",
  },
];

export const appStore = [
  {
    title: "App Store Rp150.000",
    image: "/app-store.jpeg",
    price: "Rp153.000",
    category: "App Store",
    discount: "1%",
  },
  {
    title: "Google Play Rp300.000",
    image: "/google-play.jpeg",
    price: "Rp306.000",
    category: "App Store",
    discount: "2%",
  },
  {
    title: "App Store Rp500.000",
    image: "/app-store.jpeg",
    price: "Rp39.000",
    category: "App Store",
    discount: "1%",
  },
];
